name: simple-pipeline

on:
  push:
    branches:
      - main

jobs:
  run_tests:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: npm install, make test-coverage
        run: npm install
      - name: run tests
        run: npm test
      - name: Coveralls
        uses: coverallsapp/github-action@v2
